/**
 * `claude-autopilot migrate-v4` — codemod for v4 → v5 rename.
 *
 * Scans a repo for @delegance/guardrail + guardrail CLI references and proposes
 * replacements. Writes with `--write`, restores from manifest with `--undo`.
 *
 * Mutation rules (per codex review of alpha.3 spec):
 *   - package.json: updates dependencies, devDependencies, optionalDependencies,
 *     peerDependencies. Preserves key ordering within each section. Preserves
 *     semver operator shape (^/~/>=/exact) — only rewrites the package name and
 *     bumps to ^5.0.0-alpha.
 *   - Shell scripts, Makefiles, workflow yaml, Dockerfiles: word-boundary match
 *     on `guardrail <verb>` → `claude-autopilot <verb>`, and
 *     `@delegance/guardrail` → `@delegance/claude-autopilot`.
 *   - package-lock.json: NOT touched (regenerated by npm install).
 *
 * --undo reads `.claude-autopilot/migrate-v4-manifest.json` and restores files
 * by sha256 match. Rejects restoration if the current file differs from the
 * backup's post-write hash, preventing clobber of user edits.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';

export interface MigrateV4Options {
  cwd?: string;
  write?: boolean;
  undo?: boolean;
  path?: string;
}

interface Replacement {
  pattern: RegExp;
  replace: (match: string, ...groups: string[]) => string;
  description: string;
}

interface FileResult {
  path: string;
  relPath: string;
  replacements: number;
  preview: string[];
}

interface ManifestEntry {
  path: string;
  beforeSha256: string;
  afterSha256: string;
  backupPath: string;
  timestamp: string;
}

const MANIFEST_DIR = '.claude-autopilot';
const MANIFEST_NAME = 'migrate-v4-manifest.json';

// File patterns to scan. Glob-like but hand-rolled — no dep on minimatch for this path.
const INCLUDE_EXTENSIONS = new Set([
  '.sh', '.bash', '.zsh', '.fish', '.mk', '.yml', '.yaml', '.json', '.toml', '.md',
]);
const INCLUDE_FILENAMES = new Set([
  'Makefile', 'Dockerfile', 'dockerfile', 'package.json',
  '.pre-commit-config.yaml', '.pre-commit-hooks.yaml', '.husky',
]);

const SKIP_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', '.next', '.nuxt', 'out',
  'coverage', '__pycache__', '.venv', 'venv', '.turbo',
  MANIFEST_DIR, // don't mutate our own manifest
]);

const VERBS = 'run|scan|ci|setup|doctor|init|fix|baseline|explain|ignore|costs|watch|hook|autoregress|triage|pr-desc|council|report|test-gen|mcp|lsp|worker|pr|preflight';

const TEXT_REPLACEMENTS: Replacement[] = [
  // Package name with version suffix (`@delegance/guardrail@^4`, `@delegance/guardrail@4.3.1`)
  // MUST run before the bare-name rule. Replaces the entire spec with
  // `@delegance/claude-autopilot@alpha` — the old `^4` / `4.3.1` ranges don't
  // resolve against the new package (it starts at 5.0.0).
  {
    pattern: /@delegance\/guardrail@[^\s"'`,)\]}]+/g,
    replace: () => '@delegance/claude-autopilot@alpha',
    description: '@delegance/guardrail@<version> → @delegance/claude-autopilot@alpha',
  },
  // Bare package name (no version suffix) — used in imports, package.json keys,
  // prose references. Preserves surrounding context.
  {
    pattern: /@delegance\/guardrail\b/g,
    replace: () => '@delegance/claude-autopilot',
    description: '@delegance/guardrail → @delegance/claude-autopilot',
  },
  // `npx guardrail <verb>` / `pnpm dlx guardrail <verb>` / `yarn dlx guardrail <verb>`.
  // These must run BEFORE the bare `guardrail <verb>` pattern below so the package-
  // name `guardrail` inside `npx` is replaced as a unit with its wrapper tool.
  {
    pattern: new RegExp(
      `((?:^|\\s)(?:npx|pnpm\\s+dlx|yarn\\s+dlx|bunx)\\s+)guardrail(\\s+)(${VERBS})\\b`,
      'g',
    ),
    replace: (_m, wrapper, ws, verb) => `${wrapper}@delegance/claude-autopilot@alpha${ws}${verb}`,
    description: 'npx/pnpm dlx/yarn dlx guardrail <verb> → ... @delegance/claude-autopilot@alpha <verb>',
  },
  // `guardrail <verb>` on its own line or after whitespace/punctuation
  {
    pattern: new RegExp(`(^|[\\s\`"'(])guardrail(\\s+)(${VERBS})\\b`, 'g'),
    replace: (_m, lead, ws, verb) => `${lead}claude-autopilot${ws}${verb}`,
    description: '`guardrail <verb>` → `claude-autopilot <verb>`',
  },
  // Quoted `"guardrail"` in argv-style arrays — Dockerfile CMD, exec args, etc.
  {
    pattern: new RegExp(
      `(["'])guardrail(["'])(\\s*,\\s*)(["'])(${VERBS})\\b`,
      'g',
    ),
    replace: (_m, q1, q2, sep, q3, verb) => `${q1}claude-autopilot${q2}${sep}${q3}${verb}`,
    description: '`"guardrail", "<verb>"` → `"claude-autopilot", "<verb>"`',
  },
];

// package.json needs JSON-aware handling for the dependency keys (to preserve
// semver operators and section structure), plus text replacements on the rest
// of the file (for scripts, bin references, etc).
function migratePackageJson(content: string): { updated: string; count: number } {
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(content) as Record<string, unknown>;
  } catch {
    return applyTextReplacements(content);
  }

  let count = 0;
  for (const section of ['dependencies', 'devDependencies', 'optionalDependencies', 'peerDependencies']) {
    const deps = pkg[section] as Record<string, string> | undefined;
    if (deps && typeof deps === 'object' && '@delegance/guardrail' in deps) {
      const oldRange = deps['@delegance/guardrail']!;
      const m = oldRange.match(/^(\^|~|>=|<=|>|<|=)?/);
      const operator = (m && m[1]) ?? '';
      // Rebuild the deps object preserving key order — substitute the old key
      // in place with the new one. Straight `delete` + reassign would append
      // the renamed dep at the end of its section, producing noisy diffs.
      const rebuilt: Record<string, string> = {};
      for (const [key, value] of Object.entries(deps)) {
        if (key === '@delegance/guardrail') {
          rebuilt['@delegance/claude-autopilot'] = `${operator}5.0.0-alpha`;
        } else {
          rebuilt[key] = value;
        }
      }
      pkg[section] = rebuilt;
      count++;
    }
  }

  const indent = detectJsonIndent(content);
  const newline = content.endsWith('\n') ? '\n' : '';
  const rewritten = JSON.stringify(pkg, null, indent) + newline;

  // Text replacements on the stringified form — catches `guardrail <verb>` in
  // scripts, bin paths, and any other embedded CLI invocation.
  const { updated, count: textCount } = applyTextReplacements(rewritten);
  return { updated, count: count + textCount };
}

function detectJsonIndent(source: string): number | string {
  const m = source.match(/\n( +)"/);
  if (m && m[1]) return m[1].length;
  return 2;
}

function applyTextReplacements(content: string): { updated: string; count: number } {
  let updated = content;
  let count = 0;
  for (const r of TEXT_REPLACEMENTS) {
    updated = updated.replace(r.pattern, (...args) => {
      count++;
      return r.replace(args[0], ...args.slice(1, args.length - 2));
    });
  }
  return { updated, count };
}

function shouldProcessFile(filePath: string): boolean {
  const base = path.basename(filePath);
  const ext = path.extname(filePath);
  if (INCLUDE_FILENAMES.has(base)) return true;
  if (INCLUDE_EXTENSIONS.has(ext)) return true;
  return false;
}

function collectFiles(root: string): string[] {
  const out: string[] = [];
  function walk(dir: string): void {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch { return; }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(entry.name)) continue;
        walk(full);
      } else if (entry.isFile() && shouldProcessFile(full)) {
        out.push(full);
      }
    }
  }
  walk(root);
  return out;
}

function sha256(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

function processFile(file: string): { replacements: number; original: string; updated: string; preview: string[] } {
  const original = fs.readFileSync(file, 'utf8');
  const { updated, count } = path.basename(file) === 'package.json'
    ? migratePackageJson(original)
    : applyTextReplacements(original);
  if (count === 0) return { replacements: 0, original, updated: original, preview: [] };
  const preview = diffPreview(original, updated);
  return { replacements: count, original, updated, preview };
}

function diffPreview(before: string, after: string): string[] {
  const preview: string[] = [];
  const beforeLines = before.split('\n');
  const afterLines = after.split('\n');
  const maxLines = Math.max(beforeLines.length, afterLines.length);
  for (let i = 0; i < maxLines && preview.length < 10; i++) {
    const b = beforeLines[i] ?? '';
    const a = afterLines[i] ?? '';
    if (b !== a) {
      if (b) preview.push(`  - ${b.trim().slice(0, 100)}`);
      if (a) preview.push(`  + ${a.trim().slice(0, 100)}`);
    }
  }
  return preview;
}

export async function runMigrateV4(options: MigrateV4Options = {}): Promise<number> {
  const cwd = options.cwd ?? options.path ?? process.cwd();

  if (options.undo) return runUndo(cwd);

  const files = collectFiles(cwd);
  const results: FileResult[] = [];
  let totalReplacements = 0;

  const manifest: ManifestEntry[] = [];

  for (const file of files) {
    const { replacements, original, updated, preview } = processFile(file);
    if (replacements === 0) continue;
    results.push({
      path: file,
      relPath: path.relative(cwd, file),
      replacements,
      preview,
    });
    totalReplacements += replacements;

    if (options.write) {
      // Reuse `original` from processFile — avoids a second read + prevents any
      // chance of `beforeSha256` diverging from what the transformation actually
      // consumed if the file changed mid-scan.
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const backupPath = `${file}.v4-backup.${timestamp}`;
      fs.writeFileSync(backupPath, original);
      fs.writeFileSync(file, updated);
      manifest.push({
        path: file,
        beforeSha256: sha256(original),
        afterSha256: sha256(updated),
        backupPath,
        timestamp,
      });
    }
  }

  // Emit report
  console.log(`\n\x1b[1m[migrate-v4] ${options.write ? 'Writing' : 'Dry-run — scanning'} ${cwd}\x1b[0m\n`);
  if (results.length === 0) {
    console.log('  No v4 references found.');
    return 0;
  }
  for (const r of results) {
    console.log(`  \x1b[32m${r.replacements}\x1b[0m  ${r.relPath}`);
    for (const line of r.preview.slice(0, 4)) console.log(`        \x1b[2m${line}\x1b[0m`);
  }
  console.log(`\n  ─────────────────────────────`);
  console.log(`  ${totalReplacements} replacements across ${results.length} files`);

  if (options.write) {
    const manifestDir = path.join(cwd, MANIFEST_DIR);
    fs.mkdirSync(manifestDir, { recursive: true });
    const manifestPath = path.join(manifestDir, MANIFEST_NAME);
    fs.writeFileSync(manifestPath, JSON.stringify({
      migratedAt: new Date().toISOString(),
      from: '@delegance/guardrail',
      to: '@delegance/claude-autopilot',
      entries: manifest,
    }, null, 2));
    console.log(`\n  \x1b[32m✓\x1b[0m  Applied. Manifest: ${path.relative(cwd, manifestPath)}`);
    console.log(`       Backup files suffix: .v4-backup.<timestamp>`);
    console.log(`       Restore: claude-autopilot migrate-v4 --undo`);
    console.log(`\n  Next: run \`npm install\` to sync package-lock.json.`);
  } else {
    console.log(`\n  Run with \x1b[36m--write\x1b[0m to apply (with .v4-backup files + restore manifest).`);
  }
  return 0;
}

function runUndo(cwd: string): number {
  const manifestPath = path.join(cwd, MANIFEST_DIR, MANIFEST_NAME);
  if (!fs.existsSync(manifestPath)) {
    console.error(`[migrate-v4] No manifest at ${manifestPath}. Nothing to undo.`);
    return 1;
  }
  const raw = JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as {
    migratedAt: string;
    from: string;
    to: string;
    entries: ManifestEntry[];
  };
  const restored: ManifestEntry[] = [];
  const pending: ManifestEntry[] = [];

  for (const entry of raw.entries) {
    if (!fs.existsSync(entry.path)) {
      console.error(`  \x1b[33m!\x1b[0m  ${path.relative(cwd, entry.path)} missing — skipping`);
      pending.push(entry);
      continue;
    }
    if (!fs.existsSync(entry.backupPath)) {
      console.error(`  \x1b[33m!\x1b[0m  backup missing for ${path.relative(cwd, entry.path)} — skipping`);
      pending.push(entry);
      continue;
    }
    const currentHash = sha256(fs.readFileSync(entry.path, 'utf8'));
    if (currentHash !== entry.afterSha256) {
      console.error(`  \x1b[33m!\x1b[0m  ${path.relative(cwd, entry.path)} modified since migrate — refusing to overwrite`);
      console.error(`        expected sha256=${entry.afterSha256.slice(0, 8)}, got ${currentHash.slice(0, 8)}`);
      pending.push(entry);
      continue;
    }
    const backup = fs.readFileSync(entry.backupPath, 'utf8');
    if (sha256(backup) !== entry.beforeSha256) {
      console.error(`  \x1b[33m!\x1b[0m  backup ${path.relative(cwd, entry.backupPath)} tampered — skipping`);
      pending.push(entry);
      continue;
    }
    fs.writeFileSync(entry.path, backup);
    fs.unlinkSync(entry.backupPath);
    console.log(`  \x1b[32m✓\x1b[0m  ${path.relative(cwd, entry.path)}`);
    restored.push(entry);
  }

  // Preserve manifest when any entries remain pending so --undo can be re-run
  // after the user resolves the blocker (restored their edits, fixed backup, etc).
  if (pending.length > 0) {
    fs.writeFileSync(manifestPath, JSON.stringify({
      ...raw,
      entries: pending,
    }, null, 2));
    console.log(
      `\n  Restored ${restored.length}, ${pending.length} pending. ` +
      `Manifest retained at ${path.relative(cwd, manifestPath)} — re-run --undo after resolving issues.`,
    );
    return 1;
  }

  fs.unlinkSync(manifestPath);
  console.log(`\n  Restored ${restored.length}, skipped 0.`);
  return 0;
}
