import type { Finding } from '../core/findings/types.ts';
import * as fs from 'node:fs';
import { execSync, spawnSync } from 'node:child_process';
import { appendCostLog } from '../core/persist/cost-log.ts';

export interface PrDescOptions {
  base?: string;
  post?: boolean;
  yes?: boolean;
  output?: string;
  _gitDiff?: string;
  _branchName?: string;
  _cachedFindings?: Finding[];
  _reviewEngine?: {
    review(input: { content: string; kind: string }): Promise<{
      rawOutput: string;
      usage?: { input: number; output: number; costUSD?: number };
    }>;
  };
  _cwd?: string;
}

export interface PrDescResult {
  title: string;
  body: string;
  prUrl?: string;
}

export function truncateDiff(diff: string, charLimit = 6000): string {
  if (diff.length <= charLimit) return diff;
  const remaining = diff.length - charLimit;
  return `${diff.slice(0, charLimit)}[...truncated ${remaining} chars]`;
}

export function summarizeFindings(findings: Finding[], max = 10): string {
  if (findings.length === 0) return 'None';
  const order: Record<string, number> = { critical: 0, error: 1, warning: 2, info: 3 };
  const sorted = [...findings].sort(
    (a, b) => (order[a.severity] ?? 9) - (order[b.severity] ?? 9),
  );
  return sorted
    .slice(0, max)
    .map(f => `- [${f.severity.toUpperCase()}] ${f.file}:${f.line ?? '?'} — ${f.message}`)
    .join('\n');
}

export function parseDescription(raw: string, fallback?: { branchName?: string; firstSummaryLine?: string }): { title: string; body: string } {
  const titleMatch = raw.match(/^Title:\s*(.+)$/m);
  let title = titleMatch ? titleMatch[1]!.trim() : '';
  // Fallback chain: branch-based conventional-commit title (`fix/foo-bar` →
  // `fix: foo bar`), then first summary bullet, then literal "chore: update".
  // The "chore: update" literal was the prior unconditional default — every
  // PR generated by this tool got the same title regardless of diff.
  if (!title) {
    title = deriveTitleFromBranch(fallback?.branchName) ??
            deriveTitleFromSummary(fallback?.firstSummaryLine) ??
            'chore: update';
  }
  const sepIdx = raw.indexOf('\n\n---\n');
  const body = sepIdx !== -1 ? raw.slice(sepIdx + 5).trim() : raw.replace(/^Title:.*\n?/m, '').trim();
  return { title, body };
}

const CONVENTIONAL_TYPES = new Set(['feat', 'fix', 'chore', 'docs', 'refactor', 'test', 'perf', 'style', 'ci', 'build']);

function deriveTitleFromBranch(branch?: string): string | null {
  if (!branch || branch === 'unknown' || branch === 'HEAD' || /^(main|master|develop)$/i.test(branch)) return null;
  // `fix/cost-tracker` → `fix: cost tracker`. `feature/foo` → `feat: foo`.
  const slashIdx = branch.indexOf('/');
  if (slashIdx > 0) {
    const rawPrefix = branch.slice(0, slashIdx).toLowerCase();
    const rest = branch.slice(slashIdx + 1);
    const prefix = rawPrefix === 'feature' || rawPrefix === 'features' ? 'feat'
      : rawPrefix === 'bugfix' || rawPrefix === 'hotfix' ? 'fix'
      : CONVENTIONAL_TYPES.has(rawPrefix) ? rawPrefix
      : null;
    if (prefix) {
      // Include `/` in the character class — multi-segment branches like
      // `fix/auth/session-leak` should normalize to `fix: auth session leak`,
      // not `fix: auth/session-leak`.
      const cleaned = rest.replace(/[-_/]+/g, ' ').trim();
      return cleaned ? `${prefix}: ${cleaned}` : null;
    }
    // Unknown prefix that contains a slash — treat the segment after the
    // first slash as the descriptive part and default the conventional
    // type to `chore:`. Example: `autopilot-test/validate-weights` →
    // `chore: validate weights` rather than the prefix-less
    // `autopilot test validate weights` (which fails commitlint and looks
    // half-finished in PR titles).
    const cleanedRest = rest.replace(/[-_/]+/g, ' ').trim();
    if (cleanedRest) return `chore: ${cleanedRest}`;
  }
  // No slash — return cleaned branch name, or null when it normalizes empty
  // (e.g. `_`, `---`). The caller chains via `??`, which only short-circuits
  // on null/undefined; an empty string would skip the rest of the fallback.
  const cleaned = branch.replace(/[-_/]+/g, ' ').trim();
  return cleaned || null;
}

function deriveTitleFromSummary(summaryLine?: string): string | null {
  if (!summaryLine) return null;
  // Strip leading bullet/dash and clip to ~60 chars.
  const cleaned = summaryLine.replace(/^[\s\-*•]+/, '').trim();
  if (!cleaned) return null;
  return cleaned.length > 70 ? `${cleaned.slice(0, 67)}...` : cleaned;
}

export async function runPrDesc(options: PrDescOptions): Promise<PrDescResult> {
  const branchName = options._branchName ?? getBranchName();
  const diff = options._gitDiff ?? getGitDiff(options.base);

  if (!diff.trim()) {
    process.stdout.write('No changes detected\n');
    return { title: 'No changes detected', body: '' };
  }

  const findings = options._cachedFindings ?? loadCachedFindings();
  const prompt = buildPrompt(branchName, truncateDiff(diff), summarizeFindings(findings));

  const engine = options._reviewEngine ?? (await resolveEngine() as unknown as PrDescOptions['_reviewEngine'])!;
  const start = Date.now();
  const { rawOutput, usage } = await engine.review({ content: prompt, kind: 'pr-diff' });
  // Extract first non-empty bullet from the model's Summary section as a
  // last-resort title fallback when the model didn't emit `Title: ...`.
  const firstSummaryLine = rawOutput.split('\n')
    .map(l => l.trim())
    .find(l => /^[-*•]\s/.test(l));
  const { title, body } = parseDescription(rawOutput, { branchName, firstSummaryLine });

  const formatted = `Title: ${title}\n\n---\n${body}`;

  if (options.output) {
    fs.writeFileSync(options.output, formatted, 'utf8');
  } else {
    process.stdout.write(formatted + '\n');
  }

  // Persist to cost log AFTER the output is emitted. The function itself
  // swallows write errors (see core/persist/cost-log.ts) so a read-only FS
  // or full disk doesn't kill commands that already succeeded.
  appendCostLog(options._cwd ?? process.cwd(), {
    timestamp: new Date().toISOString(),
    files: 1,
    inputTokens: usage?.input ?? 0,
    outputTokens: usage?.output ?? 0,
    costUSD: usage?.costUSD ?? 0,
    durationMs: Date.now() - start,
  });

  if (options.post) {
    return createPr(title, body, options.yes ?? false);
  }

  return { title, body };
}

function getBranchName(): string {
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

function getGitDiff(base?: string): string {
  try {
    const ref = base ?? getUpstreamBase();
    return execSync(`git diff ${ref}...HEAD`, { encoding: 'utf8' });
  } catch {
    return '';
  }
}

function getUpstreamBase(): string {
  try {
    return execSync(
      'git rev-parse --abbrev-ref --symbolic-full-name @{u}',
      { encoding: 'utf8' },
    ).trim();
  } catch {
    return 'HEAD~1';
  }
}

function loadCachedFindings(): Finding[] {
  try {
    return JSON.parse(fs.readFileSync('.guardrail-cache/findings.json', 'utf8')) as Finding[];
  } catch {
    return [];
  }
}

function buildPrompt(branch: string, diff: string, findingsSummary: string): string {
  return `Generate a pull request title and description.

Output format (must follow exactly):

Title: <one-line conventional-commit title — e.g. "fix(auth): close session leak on logout" or "feat: add SSO for enterprise tenants". Do NOT use a generic placeholder like "chore: update". Derive from the actual diff.>

---

## Summary
<3-5 bullet points describing what changed and why>

## Changes
<grouped by file/area, concise>

## Test Plan
<checklist of what to verify before merging>

Branch: ${branch}
Diff:
${diff}

Guardrail findings in this diff:
${findingsSummary}`;
}

async function resolveEngine() {
  const { loadAdapter } = await import('../adapters/loader.ts');
  const { loadConfig } = await import('../core/config/loader.ts');
  const configPath = process.env.GUARDRAIL_CONFIG ?? 'guardrail.config.yaml';
  let engineRef = 'auto';
  try {
    const cfg = await loadConfig(configPath);
    const rev = (cfg as { reviewEngine?: unknown }).reviewEngine;
    if (rev) engineRef = typeof rev === 'string' ? rev : (rev as { adapter: string }).adapter;
  } catch {
    // no config file — fall back to auto
  }
  return loadAdapter({ point: 'review-engine', ref: engineRef });
}

async function createPr(title: string, body: string, yes: boolean): Promise<PrDescResult> {
  if (!yes) {
    process.stdout.write('\nCreate PR with this description? [y/N] ');
    const answer = await new Promise<string>(resolve => {
      process.stdin.setEncoding('utf8');
      process.stdin.once('data', (chunk: string) => resolve(chunk.split('\n')[0] ?? ''));
    });
    if (!answer.toLowerCase().startsWith('y')) return { title, body };
  }
  const result = spawnSync('gh', ['pr', 'create', '--title', title, '--body', body], { encoding: 'utf8' });
  if (result.status !== 0) {
    throw new Error(`gh pr create failed: ${result.stderr?.trim() || result.error?.message || 'unknown error'}`);
  }
  const prUrl = result.stdout.trim();
  process.stdout.write(`\nPR created: ${prUrl}\n`);
  return { title, body, prUrl };
}
